package org.gwtproject.server.persistence;

import javax.persistence.*;

/**
 * AdUser generated by hbm2java
 */
@Entity
@Table(name = "ad_users", schema = "public")
public class AdUser {

    private static final long serialVersionUID = -6924170956435453207L;

    private long id;
    private String firstName;
    private String username;
    private String password;

    public AdUser() {
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @SequenceGenerator(name = "identifier", sequenceName = "ad_users_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "identifier")
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "first_name", nullable = false, length = 80)
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firtsName) {
        this.firstName = firtsName;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "user_name", nullable = false, length = 100)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
